"""add task_dag_nodes and task_artifacts tables

Revision ID: 3e2233c618f3
Revises: aac2aef7e6e1
Create Date: 2026-05-19 09:44:42.446954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e2233c618f3'
down_revision: Union[str, None] = 'aac2aef7e6e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_artifacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.String(length=50), nullable=True, comment='关联的 DAG 节点 ID'),
    sa.Column('file_path', sa.String(length=500), nullable=False, comment='文件路径'),
    sa.Column('content', sa.Text(), nullable=False, comment='文件内容'),
    sa.Column('language', sa.String(length=20), nullable=True, comment='编程语言'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_artifacts_task_id'), 'task_artifacts', ['task_id'], unique=False)
    op.create_table('task_dag_nodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.String(length=50), nullable=False, comment='DAG 内节点标识'),
    sa.Column('agent', sa.String(length=50), nullable=False, comment='执行的 Agent 类型'),
    sa.Column('label', sa.String(length=255), nullable=True, comment='节点显示标签'),
    sa.Column('description', sa.Text(), nullable=True, comment='节点详细描述'),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='dagnodestatus'), nullable=True),
    sa.Column('depends_on', sa.JSON(), nullable=True, comment='依赖的节点 ID 列表'),
    sa.Column('input_data', sa.JSON(), nullable=True, comment='节点输入数据'),
    sa.Column('output_data', sa.JSON(), nullable=True, comment='节点输出数据'),
    sa.Column('error_msg', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('duration_ms', sa.Integer(), nullable=True, comment='执行耗时(ms)'),
    sa.Column('token_usage', sa.Integer(), nullable=True, comment='Token 消耗'),
    sa.Column('cost_usd', sa.String(length=20), nullable=True, comment='费用'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_dag_nodes_task_id'), 'task_dag_nodes', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_dag_nodes_task_id'), table_name='task_dag_nodes')
    op.drop_table('task_dag_nodes')
    op.drop_index(op.f('ix_task_artifacts_task_id'), table_name='task_artifacts')
    op.drop_table('task_artifacts')
    # ### end Alembic commands ###
