"""add deployments table

Revision ID: 5053db2ce5ee
Revises: c5392f45737a
Create Date: 2026-05-20 01:59:58.323930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5053db2ce5ee'
down_revision: Union[str, None] = 'c5392f45737a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('BUILDING', 'RUNNING', 'STOPPED', 'FAILED', name='deploystatus'), nullable=True),
    sa.Column('container_id', sa.String(length=100), nullable=True),
    sa.Column('preview_url', sa.String(length=500), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('build_log', sa.Text(), nullable=True),
    sa.Column('dockerfile', sa.Text(), nullable=True),
    sa.Column('compose_yaml', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('stopped_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployments_task_id'), 'deployments', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deployments_task_id'), table_name='deployments')
    op.drop_table('deployments')
    # ### end Alembic commands ###
