"""add token_usage cost_usd error_msg to task_steps

Revision ID: aac2aef7e6e1
Revises: 2fe1f52babe3
Create Date: 2026-05-19 09:32:01.080987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aac2aef7e6e1'
down_revision: Union[str, None] = '2fe1f52babe3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_steps', sa.Column('token_usage', sa.Integer(), nullable=True, comment='Token消耗'))
    op.add_column('task_steps', sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True, comment='费用(USD)'))
    op.add_column('task_steps', sa.Column('error_msg', sa.Text(), nullable=True, comment='错误信息'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_steps', 'error_msg')
    op.drop_column('task_steps', 'cost_usd')
    op.drop_column('task_steps', 'token_usage')
    # ### end Alembic commands ###
