"""add error_logs and retry_history

Revision ID: b0cf241ca266
Revises: a092071c6033
Create Date: 2026-05-20 01:36:08.751560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0cf241ca266'
down_revision: Union[str, None] = 'a092071c6033'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('error_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.String(length=50), nullable=True),
    sa.Column('error_type', sa.String(length=50), nullable=True, comment='syntax, runtime, timeout, llm_error'),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('is_recoverable', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_error_logs_task_id'), 'error_logs', ['task_id'], unique=False)
    op.create_table('retry_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.String(length=50), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=True),
    sa.Column('strategy', sa.String(length=50), nullable=True, comment='retry, fix_and_retry, model_switch'),
    sa.Column('model_used', sa.String(length=50), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False, comment='success or failed'),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retry_history_task_id'), 'retry_history', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_retry_history_task_id'), table_name='retry_history')
    op.drop_table('retry_history')
    op.drop_index(op.f('ix_error_logs_task_id'), table_name='error_logs')
    op.drop_table('error_logs')
    # ### end Alembic commands ###
