"""add agent_metrics and execution_snapshots

Revision ID: c5392f45737a
Revises: b0cf241ca266
Create Date: 2026-05-20 01:49:19.215905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5392f45737a'
down_revision: Union[str, None] = 'b0cf241ca266'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.String(length=50), nullable=True),
    sa.Column('agent', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_metrics_agent'), 'agent_metrics', ['agent'], unique=False)
    op.create_index(op.f('ix_agent_metrics_task_id'), 'agent_metrics', ['task_id'], unique=False)
    op.create_table('execution_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.String(length=50), nullable=True),
    sa.Column('step_index', sa.Integer(), nullable=True),
    sa.Column('event', sa.String(length=50), nullable=False),
    sa.Column('state', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_snapshots_task_id'), 'execution_snapshots', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_execution_snapshots_task_id'), table_name='execution_snapshots')
    op.drop_table('execution_snapshots')
    op.drop_index(op.f('ix_agent_metrics_task_id'), table_name='agent_metrics')
    op.drop_index(op.f('ix_agent_metrics_agent'), table_name='agent_metrics')
    op.drop_table('agent_metrics')
    # ### end Alembic commands ###
